# Generated by Django 6.0.4 on 2026-04-09 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Remote', 'Remote'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=50)),
                ('experience_level', models.CharField(choices=[('Entry Level', 'Entry Level (0-2 years)'), ('Mid Level', 'Mid Level (3-5 years)'), ('Senior Level', 'Senior Level (5+ years)'), ('Lead/Manager', 'Lead/Manager')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('salary_range', models.CharField(blank=True, help_text='e.g., $30k - $50k', max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='List requirements, one per line or bullet points')),
                ('responsibilities', models.TextField(help_text='List responsibilities, one per line or bullet points')),
                ('benefits', models.TextField(blank=True, help_text='List benefits, one per line or bullet points')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Careers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CEOMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CEO', max_length=100)),
                ('title', models.CharField(default='Chief Executive Officer', max_length=100)),
                ('message', models.TextField()),
                ('quote', models.CharField(blank=True, help_text='Inspirational quote', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ceo/')),
                ('avatar_initial', models.CharField(default='CE', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CEO Message',
                'verbose_name_plural': 'CEO Messages',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('quote', models.TextField(blank=True, help_text='Personal quote or message from team member')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('avatar_initial', models.CharField(help_text='Two letters for avatar', max_length=2)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('social_linkedin', models.URLField(blank=True)),
                ('social_twitter', models.URLField(blank=True)),
                ('social_github', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('portfolio_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.career')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
